version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.port=9200"
      - "http.cors.allow-origin=*"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    volumes:
      - ${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data
    networks:
      operations_intranet:
        ipv4_address: 172.30.91.2
        aliases:
          - elasticsearch
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet
    ulimits:
      memlock:
        soft: -1
        hard: -1

  dejavu:
    image: appbaseio/dejavu:latest
    container_name: dejavu
    networks:
      operations_intranet:
        ipv4_address: 172.30.91.6
        aliases:
          - dejavu
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  fluentd:
    build: ./fluentd
    image: registry.liquibrium.com/fluentd
    container_name: fluentd
    external_links:
      - container-registry
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ${DATA_DIR}/logs:/logs
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "9880:9880"
      - "9880:9880/udp"
    networks:
      operations_intranet:
        ipv4_address: 172.30.91.3
        aliases:
          - fluentd
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ${DATA_DIR}/kibana/:/usr/share/kibana/config/
    networks:
      operations_intranet:
        ipv4_address: 172.30.91.4
        aliases:
          - kibana
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  proxy-kibana:
    build: ./proxy-kibana
    image: registry.liquibrium.com/proxy-kibana
    container_name: kibana-proxy
    external_links:
      - container-registry
    depends_on:
      - kibana
    environment:
      VIRTUAL_HOST: logs.liquibrium.local
      NETWORK_ACCESS: internal
    networks:
      operations_intranet:
        ipv4_address: 172.30.91.5
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet
          - node.labels.proxy == true

  proxy-dejavu:
    build: ./proxy-dejavu
    image: registry.liquibrium.com/proxy-dejavu
    container_name: dejavu-proxy
    external_links:
      - container-registry
    depends_on:
      - dejavu
    environment:
      VIRTUAL_HOST: dejavu.liquibrium.local
      NETWORK_ACCESS: internal
    networks:
      operations_intranet:
        ipv4_address: 172.30.91.7
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet
          - node.labels.proxy == true

networks:
  operations_intranet:
    external: true
