services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: logs-elasticsearch
    restart: always
    dns: ${DNS_IP_INTERNAL}
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://logs-elasticsearch:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"]
      interval: 5s
      timeout: 3s    
    external_links:
      - operations:dns
    env_file:
      - ./elasticsearch.env
    volumes:
      - ${DB_DIR}/logselasticsearch:/usr/share/elasticsearch/data
    ports:
      - "${LOG_SERVER_IP}:9200:9200"
    networks:
      operations_intranet:
        ipv4_address: 172.34.19.2
        aliases:
          - elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1

  dejavu:
    image: appbaseio/dejavu:latest
    container_name: logs-dejavu
    restart: $(RESTART}
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations:dns
    depends_on:
      - elasticsearch
    networks:
      operations_intranet:
        ipv4_address: 172.34.19.3
        aliases:
          - dejavu
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: logger.finsec.localdomain:24224
    #     tag: "{{.Name}}.{{.ID}}"
    #     fluentd-async: "true"
    #     fluentd-max-retries: "144"
    #     fluentd-retry-wait: "600s"        

  fluentd:
    build: ./fluentd
    image: registry.finsec.localdomain/fluentd
    container_name: logs-fluentd
    dns: ${DNS_IP_INTERNAL}
    restart: always
    external_links:
      - operations:dns
    depends_on:
      - elasticsearch
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ${DATA_DIR}/logs/fluentd:/logs
    ports:
      - "${LOG_SERVER_IP}:24224:24224"
      - "${LOG_SERVER_IP}:24224:24224/udp"
      - "${LOG_SERVER_IP}:9880:9880"
      - "${LOG_SERVER_IP}:9880:9880/udp"
    networks:
      operations_intranet:
        ipv4_address: 172.34.19.4
        aliases:
          - fluentd

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.1
    container_name: logs-kibana
    dns: ${DNS_IP_INTERNAL}
    restart: $(RESTART}
    external_links:
      - operations:dns
    depends_on:
      - elasticsearch
      - fluentd
    environment:
      ELASTICSEARCH_URL: http://logs-elasticsearch:9200
    volumes:
      - ${DATA_DIR}/logs/kibana/:/usr/share/kibana/config/
    networks:
      operations_intranet:
        ipv4_address: 172.34.19.5
        aliases:
          - kibana
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: logger.finsec.localdomain:24224
    #     tag: "{{.Name}}.{{.ID}}"
    #     fluentd-async: "true"
    #     fluentd-max-retries: "144"
    #     fluentd-retry-wait: "600s"        

  kibana-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: logs-kibana-proxy-internal
    dns: ${DNS_IP_INTERNAL}
    restart: $(RESTART}
    external_links:
      - operations:dns
      - operations:proxy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://logs-kibana-proxy-internal"]
      interval: 300s
      timeout: 120s
      start_period: 100s
      retries: 5
    depends_on:
      - kibana
      - fluentd
    environment:
      VIRTUAL_HOST: logs.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./kibana-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      operations_intranet:
        ipv4_address: 172.34.19.6
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: logger.finsec.localdomain:24224
    #     tag: "{{.Name}}.{{.ID}}"
    #     fluentd-async: "true"
    #     fluentd-max-retries: "144"
    #     fluentd-retry-wait: "600s"        

  dejavu-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: logs-dejavu-proxy-internal
    dns: ${DNS_IP_INTERNAL}
    restart: $(RESTART}
    depends_on:
      - dejavu
      - fluentd
    external_links:
      - operations:dns
      - operations:proxy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://logs-dejavu-proxy-internal"]
      interval: 300s
      timeout: 120s
      start_period: 100s
      retries: 5
    environment:
      VIRTUAL_HOST: dejavu.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./dejavu-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      operations_intranet:
        ipv4_address: 172.34.19.7
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: logger.finsec.localdomain:24224
    #     tag: "{{.Name}}.{{.ID}}"
    #     fluentd-async: "true"
    #     fluentd-max-retries: "144"
    #     fluentd-retry-wait: "600s"        

  elasticvue:
    image: cars10/elasticvue
    container_name: logs-elasticvue
    dns: ${DNS_IP_INTERNAL}
    restart: $(RESTART}
    external_links:
      - operations:dns
    depends_on:
      - elasticsearch
      - fluentd
    networks:
      operations_intranet:
        ipv4_address: 172.34.19.8
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: logger.finsec.localdomain:24224
    #     tag: "{{.Name}}.{{.ID}}"
    #     fluentd-async: "true"
    #     fluentd-max-retries: "144"
    #     fluentd-retry-wait: "600s"        
        
  elasticvue-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: logs-elasticvue-proxy-internal
    dns: ${DNS_IP_INTERNAL}
    restart: $(RESTART}
    depends_on:
      - elasticvue
      - fluentd
    external_links:
      - operations:dns
      - operations:proxy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://logs-elasticvue-proxy-internal"]
      interval: 300s
      timeout: 120s
      start_period: 100s
      retries: 5
    environment:
      VIRTUAL_HOST: elastic.logs.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./elasticvue-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      operations_intranet:
        ipv4_address: 172.34.19.9
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: logger.finsec.localdomain:24224
    #     tag: "{{.Name}}.{{.ID}}"
    #     fluentd-async: "true"
    #     fluentd-max-retries: "144"
    #     fluentd-retry-wait: "600s"        

networks:
  operations_intranet:
    external: true
